apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sb-demo
  name: sb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sb-demo
    spec:
      containers:
      - image: aburilovic/dockersandbox:1.0.5
        name: sb-demo
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper:3.7
        name: zookeeper
        env: 
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - image: bitnami/kafka:3.0.2
        name: kafka
        env: 
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        resources: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:25.0.6
        args: ["start-dev", "--import-realm"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-export-volume
          mountPath: /opt/keycloak/data/import
      volumes:
      - name: keycloak-export-volume
        hostPath:
          #minikube mount needed -> minikube mount /home/aburilovic/keycloak_export:/mnt/keycloak_export
          path: /mnt/keycloak_export 
          type: Directory











