apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sb-demo
  name: sb-demo
spec:
  ports:
  - name: http
    port: 8081
    nodePort: 30010
  selector:
    app: sb-demo
  type: NodePort
status:
  loadBalancer: {}
  
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
  - name: http
    port: 2181
  selector:
    app: zookeeper
  type: ClusterIP
status:
  loadBalancer: {}
  
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
spec:
  ports:
  - name: http
    port: 9092
  selector:
    app: kafka
  type: ClusterIP
status:
  loadBalancer: {}
