version: '3.8'  # Specify the version of Docker Compose

services:
  kafka:
    image: bitnami/kafka:3.0.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  spring-boot-app:
    image: aburilovic/dockersandbox:0.0.1-SNAPSHOT
    container_name: spring_boot_app
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      # Set the active profile here (dev or prod)
      - SPRING_PROFILES_ACTIVE=prod

networks:
  default:
    name: kafka-network
    
